---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-nextcloud
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/component: app
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-ca-store
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud-ca-store
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/component: app
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Mi"