---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-collabora
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: collabora
    app.kubernetes.io/instance: nextcloud
data:
  username: YWRtaW4=
  password: dHoyTEtoTzBocDBJdzJTNA==

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-mariadb
  namespace: nextcloud
  labels:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: mariadb
type: Opaque
data:
  mariadb-username: "bmV4dGNsb3Vk"
  mariadb-password: "SFFhbmNyNEFIN0pEc2VBYg=="
  mariadb-root-password: "Z0FlWVlJT1hJaw=="

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-redis
  namespace: nextcloud
  labels:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: redis
type: Opaque
data:
  redis-password: "VkFXTWdsUDNtTVVSR2hqMg=="

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-whiteboard
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: whiteboard
    app.kubernetes.io/instance: nextcloud
type: Opaque
data:
  whiteboard-jwt-key: "TzdMQU41QnJCdjgwRzFFYQ=="

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
type: Opaque
data:
  db-username: "bmV4dGNsb3Vk"
  db-password: "SFFhbmNyNEFIN0pEc2VBYg=="

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
type: Opaque
data:
  nextcloud-username: "YXV0b21hdGlvbg=="
  nextcloud-password: "dGhpc2lzdGhlZGVmYXVsdHBhc3NwaHJhc2U="
