---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: nextcloud-mariadb
  namespace: nextcloud
  labels:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: mariadb

---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: nextcloud-redis-master
  namespace: nextcloud
  labels:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: redis

---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: nextcloud-redis-replica
  namespace: nextcloud
  labels:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: redis