apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls
  namespace: keycloak
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUvekNDQXVlZ0F3SUJBZ0lVV2xsRWh1YnVq
    a2hpN1NZWExiOTNSUmROb0hzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2F6RUxNQWtHQTFVRUJoTUNW
    Vk14RGpBTUJnTlZCQWdNQlZOMFlYUmxNUTB3Q3dZRFZRUUhEQVJEYVhSNQpNUk13RVFZRFZRUUtE
    QXBOWVdsdVUzbHpkR1Z0TVFzd0NRWURWUVFMREFKSlZERWJNQmtHQTFVRUF3d1NUV0ZwCmJsTjVj
    M1JsYlNCU2IyOTBJRU5CTUI0WERUSTJNRE13TXpBMk5EYzBObG9YRFRJNE1EWXdOVEEyTkRjME5s
    b3cKWkRFTE1Ba0dBMVVFQmhNQ1ZWTXhEakFNQmdOVkJBZ01CVk4wWVhSbE1RMHdDd1lEVlFRSERB
    UkRhWFI1TVJNdwpFUVlEVlFRS0RBcE5ZV2x1VTNsemRHVnRNUXN3Q1FZRFZRUUxEQUpKVkRFVU1C
    SUdBMVVFQXd3TGJXRnBiaTV6CmVYTjBaVzB3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3
    QXdnZ0VLQW9JQkFRQ2ZINjI5NHBUYkNMN1UKSzZsNzEvVlN6UGVFOVRIZVpRYkR4YTB2VCtIR3dn
    TDNHUTk3RlR6UXNjaTQyWEt4aXBmanpRa2FuY2JWTTkzYQpTcE9mT0tJRjBLc3JsQjh1WXNrQm9i
    SjhLT3lUM0l3SkdQRE1OU1ZmVDNYUTB4VW5pQXA0RmNqa1BSN20va09YCnVqakRRYlZNTkJUM0k3
    aWlxSmx0akd6RlpoVmNVZ2E2UXlacmZhZkJPUVBGcHVKeHB0VjlsbFA3UUNwOTBTdE4KZjNwcGc1
    M2grRWlENzBQbnhWQkhXZHhJRkRBSVJEcWowa2JXWU9pVTRmTThyb0FyZ1lFV0JZSjNEczBVeWR5
    SwppcVVpM1dXV3FWRUkyS2VwdzIxL05OQ0lrcXNISEIwK2cxYlpKbVpFWUgwZjhpQTVNVVNLc2R2
    RVM5REwxQ3pECmJoaXBiOGZkQWdNQkFBR2pnYUV3Z1o0d1hBWURWUjBSQkZVd1U0SVZZMjlzYkdG
    aWIzSmhMbTFoYVc0dWMzbHoKZEdWdGdoVnVaWGgwWTJ4dmRXUXViV0ZwYmk1emVYTjBaVzJDRkd0
    bGVXTnNiMkZyTG0xaGFXNHVjM2x6ZEdWdApnZzBxTG0xaGFXNHVjM2x6ZEdWdE1CMEdBMVVkRGdR
    V0JCUVQzY28wdUxFeWllMkNsMEZKZGJFbWNuRVJXakFmCkJnTlZIU01FR0RBV2dCVFFQdlhZbU9j
    M2FSMkNqMTlSTVFlU3kxTUQ1akFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQWdFQUZudHc5N1pRZUlC
    eXhGREU1bUplZEEwOGwzdEVZVjh2NllkZ01rY0pzckpiNEVnWTgwcXM0YW5rZUI1UwpLbjN1TFE5
    RFVpc2lDMjZqcEV5U2NxeDA4Vjk4akQrbTYxTWtKRnVlazA3YjJVbjBtQVZ6T1BSSk82aVRPbTdz
    CnVQZlU5VTVtVmpqUVN3RlU1MC9LeEtsQTQyb2RFMFJzTEg4TEFZcjFabG1aRWw4Rlh2WkJ1a3hs
    RGhlU29sMEMKblhJMmNZZVlSanVoUEpOdlMrcmlpMEgwRmk5YnZ3UkdwWlhwakV3U1lydUFvSzAr
    aGNrMFVzK3o5T0dDNFlhVgo3U1k2azBDc092OFhFQjhVeXdnYnovL1k0c1k4b0Q0WDdFbFBNNVVy
    MHNXMHcyTDhiOXhvM1B2K0JaWUpOb2ZkCi82Z2prSTN2SmpQS1VDWTZDVlhYNVBHc1BjYmtLYmtX
    M2Y0Uis3NjdnbzNXaGhkWHlmSmgrRGRkajFxeTQ3VXkKSWV6aUhucUE1RndaMTBIK09Fb0V4RDB6
    cXR2NXQzRU92RVlLaGRjQkdTcGptNjFsK2xMWEJLQ3RCTkF6THNXRAphL3BxblRGN3lFaFZNVGlC
    ODZVSFpCU0lJVFU3Z08xbXRxQlBVMnM5eXpMeVlXYmp2SEJZY3A0c210aDVGZFk0CkUvajlwOXJB
    VnJYK1ZSL0NEeDVCWHl6OTlobkR1TFFTUi9yQlBUWlcwLy9FVU4yeGJ3emxVN2ZBWHc3WTFRV3gK
    bnF6eTlmMkxlTnZ5bm9rM2RWSkIydlE1SkZ0TkZibTltamRaWkJhN3FTMHJFblhaNnBUbW1rSWEw
    cWFBQ05DeApBakhMM2xKZmlrTVhCSmRaM2NXelREd2dPeFRDZ0syR0pPVEVidU5SNGwvaVVVcz0K
    LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktrd2dnU2xBZ0VBQW9JQkFRQ2ZINjI5NHBUYkNMN1UKSzZsNzEvVlN6UGVFOVRIZVpRYkR4
    YTB2VCtIR3dnTDNHUTk3RlR6UXNjaTQyWEt4aXBmanpRa2FuY2JWTTkzYQpTcE9mT0tJRjBLc3Js
    Qjh1WXNrQm9iSjhLT3lUM0l3SkdQRE1OU1ZmVDNYUTB4VW5pQXA0RmNqa1BSN20va09YCnVqakRR
    YlZNTkJUM0k3aWlxSmx0akd6RlpoVmNVZ2E2UXlacmZhZkJPUVBGcHVKeHB0VjlsbFA3UUNwOTBT
    dE4KZjNwcGc1M2grRWlENzBQbnhWQkhXZHhJRkRBSVJEcWowa2JXWU9pVTRmTThyb0FyZ1lFV0JZ
    SjNEczBVeWR5SwppcVVpM1dXV3FWRUkyS2VwdzIxL05OQ0lrcXNISEIwK2cxYlpKbVpFWUgwZjhp
    QTVNVVNLc2R2RVM5REwxQ3pECmJoaXBiOGZkQWdNQkFBRUNnZ0VBSzdZVkVTdHovck5wVUhscUJt
    WXRzd0F4SW1vRXQvWUNwTGJodXpSemJoa1AKblhkWjVGTFNNUFlWa0luVFV1Z2lqMlpja040MHA0
    Nm02L2MrbENlSGdwZHUzZnJEa2dkNjlpTElHQWxaNjhoVApBNURCWFNkZ1M4MVZMUGMvUVd2Q2pI
    aFhoak13RVA1WjdRMHYySnR0UlRDdGJiSjNYdDkzdmpzc0NoSGYza3NPCm5WMUU0aHE4Q0Rkb1ow
    dVJjTjVkTDlOVStvOGxzMEc5RVBESlJBOG9DRitWYjNzOHhYcWovY3h4ek1JSXpWYnoKN0QyejF0
    dHBzbGlodDRqSkxFdFV2c3NqS0hac1ZrU01HS1B4ZGlEZTJFZm5hRitoRG54cnQxWVdJWDVkSkRD
    VApLU3FqOFhQeVIvQVR5YkVoT0l2aTZZUG9NUGJKbGlUTHYydzEzdjFVMVFLQmdRRGdyOG5xaTg3
    VklORk5vUFZSClBxRTdQNHUxaHZGSC8ra3ZVNnRhdmtpZVU5ckxIVDUvaThVaUFYaEM2UUg5T290
    NDl2TXhjb3hMZHRybmJRQUUKRitIaVI4R1NDZ1hCTmtKTWZlQ0Y5K0tta3lUc2x6a2pBaUtxRFVJ
    ajc1WlAvNlNsSjY4SXd1UjdjK1dMelNsSApnUUR2am9qcmRZTlduZEs4Z0UxVmE1dVRKd0tCZ1FD
    MVRNaEs4UVczNU5wdHJ1V1NyQVY1UnkxdWs5L2FPVzV0CnF3MS9kTHZtWU9NbUJPdGdycWVrS2R5
    b0E5TWNlUjM0UDVHWk16V1NMNGNKd3VCbWlFM3c0WVZPK3JwWG94UDIKM3R5aEZGWTFaL1NlcnpW
    eU9XY3kyTTJOd3I0UVNDRGRmcDl5d2pTY2VwWlZnV21odFIyai9Cc0pMaHN2c25WRwpaVmR2RHFG
    Zld3S0JnUUNucUtUTDN1MUV2Z3RRbU9YVmJSMlVmM041emlybkpmL1RyK1J5ZndEakhBRnNoUExv
    CjY5djY1d3ZkS2MreExPbDhKeElMZU1WVlhtZzBQbksvbXk2VDBpV1FHdWgyWjAyTGxIWmdvVHRB
    UHhaVGNQaFMKdGpvMW1GVWRTWjlwTElLb05uZDIyeTd4SytkQ3JhRzYySGxoU0lQRTUxaE0zdEdz
    bFRTZm8vOWdDd0tCZ1FDVAp2bW11NExGM1JiRlhGdU1RM3N4ckk3ejdVdGhtZnN6bDVESlF2ckZ0
    TVdHS2x4RzFyVDhDUWZjR21HOU8wY2pCCmlCUS8wNEtCaWVleTViTjIrdmNCS05jNUlJd0FaTzRk
    RFVxZ25mRU8vcE5UU1piMWFhQVd5S1RpTkdRczRvcWQKMWRWY2NMVHRHOTBzK3hRNDZsNm9Sd2RG
    T09TQXZ4NWc2cThRMnN4WTV3S0JnUURSd3cydG52TjhQSEFsUUVOWQpYblNIRnFYcjBtVnFSL242
    SlZaR3A3R3lyT2xhcGI3VGlmTjUvNUd1Ukw5cVZiNTdVQzN4ckM2YVNMeXZKUzRECi9uWFROYmw5
    Y21uUTJUbzVsbkRPOFdmeFNBSnNtSFNReFRJd09JZWVnVXNoUHdjbWdaOFZsWUtCbE5aZWIzUWUK
    VHFzOFE4UFZlaHdpdnNpQjhabjJSNE1wd1E9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==


---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-ca
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak-ca
    app.kubernetes.io/instance: keycloak
type: Opaque
data:
  rootca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ0ekNDQTUrZ0F3SUJBZ0lVQWNtM1Z4b3hx
    OVFNNWNjN0Rwbmd5QWJZekMwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2F6RUxNQWtHQTFVRUJoTUNW
    Vk14RGpBTUJnTlZCQWdNQlZOMFlYUmxNUTB3Q3dZRFZRUUhEQVJEYVhSNQpNUk13RVFZRFZRUUtE
    QXBOWVdsdVUzbHpkR1Z0TVFzd0NRWURWUVFMREFKSlZERWJNQmtHQTFVRUF3d1NUV0ZwCmJsTjVj
    M1JsYlNCU2IyOTBJRU5CTUI0WERUSTJNRE13TXpBMk5EYzBObG9YRFRNMk1ESXlPVEEyTkRjME5s
    b3cKYXpFTE1Ba0dBMVVFQmhNQ1ZWTXhEakFNQmdOVkJBZ01CVk4wWVhSbE1RMHdDd1lEVlFRSERB
    UkRhWFI1TVJNdwpFUVlEVlFRS0RBcE5ZV2x1VTNsemRHVnRNUXN3Q1FZRFZRUUxEQUpKVkRFYk1C
    a0dBMVVFQXd3U1RXRnBibE41CmMzUmxiU0JTYjI5MElFTkJNSUlDSWpBTkJna3Foa2lHOXcwQkFR
    RUZBQU9DQWc4QU1JSUNDZ0tDQWdFQXlIZ0YKRFBOVEVpcDFoM2ZKTkx0aVp2UW9Zb1ZMUWxlZlZz
    UjdGUDlXNHhHWTlwSmpheFNBNFNjYzFGN3pMeDNjblE1agpVdjBrOHVFT2diQndEL2ljd0NQYTQw
    K1NyOFhuWENER3dpeGJqcVkrVklRd1IvMlFMNzBnSnRJK3Z4eUNHeTFFCmxoV29GWGZXcmlRRngy
    U0Q4NXVDU2V1VWw1MStjTlBxbnpMR0NvV2RSRDYvVGdvUktFYjRlV0k2bTJoR0VXNmkKWmQ1Rlg4
    ZnpzR0ZOWnArazlxZHZpTHFFSEF0QWRvMlA5cGFhTDdrSTd1dVBIV1N5aVRQWlZyNFg0YkxzVkFn
    cgpsc0FPL1FHVGIxUWZjRjgzenNVYzQ2R2hEaDUrWWRCMGhWMVpCMzhxQVAvamNBcTJjTTlkV0xq
    NnBQM3U2WjQ2CkJpTGlwYnYwbnlpdXlWdXgvYW9RaFRGOTNoeHJwK3l1UjhkajlwMHEvSVoyWFdD
    dElzeGJlNGl4dkJDaFc3MmQKNGdsQ280SlJXWCtydFQ4amZRaXR1SXZwam1NZW1tWnRTaHNiekw2
    TmluWVkvNW9OV2NiWTVqZDJFc3BFRGY1NgpuN3hWMExTaTV2Yk1yZ1JqNk95ZHZOYTJ2OG9kUXBS
    WExaMno2bGJRVnpDMHVGaml3R1U1cVJqeUQraXc4dDJXCnAyL0ZmaUtwZGxBckMxV25tWjR0MXlo
    eTJSM2RjaHphNG5neUxWUU84VFhiNW4zc04wSDI5eGY2OGhCeGFWMkEKS1U2QmxOOFhBbFZhazYr
    R1plblBSUWtOTS95a1ZGMUxGN2lkWXBQUXZpcmZ3OXB6cCtnVjFQV1ZDSkowYkY1cwpFVXdaeTg2
    bEx1TUJGTkZnMzVadUFwY0FoRmZGYWlWc1R2WC9zTzhDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllF
    CkZOQSs5ZGlZNXpkcEhZS1BYMUV4QjVMTFV3UG1NQjhHQTFVZEl3UVlNQmFBRk5BKzlkaVk1emRw
    SFlLUFgxRXgKQjVMTFV3UG1NQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVM
    QlFBRGdnSUJBRE5rbDhpcwp2WFE5NGJwMmtPSzJBQ0Rob0QzT05WWUpDaS9ueUpLSi95SFMxbHVz
    N2U0WmFkeTBkMnRTKzQ0Nm9zTDFxQk0zCktpZXd4QU1RUnMrYWkxUW11VGZLVVcwZ2twTWE2TlVs
    U0JCNHRqaERTYXJtL2tobVdvWEJhN0s0K25mamU1dVUKVGJFdVJhVkZMdjdJNG5vbWdJTEY0N1Zv
    anZQMzZBRXNpVitYKysrWm9OeVFyVnJSYWwxeEhrVkxsdE9QaGVlTgpRaW5IZGJtQ3BqSU9WZ1hq
    dXZ6d2VMN2FpS1BYOVd0ZHhsaGRYQUxkV3pGS3J5bEpreDhpTDFBNHVJQTBzWVh6CjZvNXRCMUlP
    MkxyaVptMGlVUkZwOHR3dERYMUhQOHd0K1Fnb0k3WTVCb3EvWXZobzk1Yk5oTzdWeVQ2NHU1MEkK
    U0huZTFWNXk4VkM4VWkwMjg5V2hYcTljb21TVHFPU1NRNmRUcDFtYzNhM3JvS01KUE1YVnQ1TDYy
    QWx6d3dOeAo1Qml4YTFjb1NlaGxMdkVJYlYveUFtMFpmdE5BTi9Pc1dDdWZQdS9JNUxJaFNGbmpw
    cURZVzV6NXprN1N4L2ZCCjYzY0ZzRjFqSVB6blpLMUg1N0NXWlJSNHV5REl6dERkcGk3dUcvVFNX
    RURha0dvRHIvNjRmY3ZiTEhZSnowTDUKTjdPRDlSM0FEZStGWXkzVkdWTkpEUlBEVHlwL1dnQkdQ
    bldIREhNREV4a1M1N1QvSHZuVVdoYXlWRVpQenB2cgpmRnRxVndqWWEwZnNMUVFqWDRMRXVzUXU1
    VU5nelF0N0RWSFRtTmlHaDE5RWk2SGIvWXNmOGJ3YlNvWGJCRUlRClhKUzlJenBrQ3F6ZkhpeHUz
    MUZxTTNld0RzWXdhdUtEZm1RaQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==


