---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env-vars
  namespace: "keycloak"
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: keycloak
data:
  BITNAMI_DEBUG: "false"
  KEYCLOAK_PRODUCTION: "false"
  KC_LOG_LEVEL: "INFO"
  KC_LOG_CONSOLE_OUTPUT: "default"
  KC_BOOTSTRAP_ADMIN_USERNAME: "user"
  KC_BOOTSTRAP_ADMIN_PASSWORD_FILE: /opt/bitnami/keycloak/secrets/admin-password
  KC_HTTP_PORT: "8080"
  KC_HTTP_MANAGEMENT_PORT: "9000"
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME: "http://keycloak.main.system/"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "false"
  KC_DB_URL: "jdbc:postgresql://keycloak-postgresql:5432/bitnami_keycloak?currentSchema=public"
  KC_DB_SCHEMA: "public"
  KC_DB_PASSWORD_FILE: /opt/bitnami/keycloak/secrets/db-password
  KC_DB_USERNAME: "keycloak"
  KC_CACHE: "ispn"
  KC_CACHE_STACK: "jdbc-ping"
  KC_CACHE_CONFIG_FILE: "cache-ispn.xml"
  JAVA_OPTS_APPEND: "-Djgroups.dns.query=keycloak-headless.keycloak.svc.main.system"
  KC_HTTP_RELATIVE_PATH: "/"
  KC_SPI_ADMIN_REALM: "master"
