---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql
  namespace: keycloak
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: postgresql
type: Opaque
data:
  postgres-password: "VzExMmxmWVlTQg=="
  password: "Q0VnU1dxRnN6ZQ=="

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: keycloak
type: Opaque
data:
  admin-password: "a1JFeXlESFJSRQ=="