apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-tls
  namespace: nextcloud
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2VENDQXRHZ0F3SUJBZ0lVYlMzOGdBalpI
    RWpqMU1iWDliWm5wbFZmYm5Fd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2F6RUxNQWtHQTFVRUJoTUNW
    Vk14RGpBTUJnTlZCQWdNQlZOMFlYUmxNUTB3Q3dZRFZRUUhEQVJEYVhSNQpNUk13RVFZRFZRUUtE
    QXBOWVdsdVUzbHpkR1Z0TVFzd0NRWURWUVFMREFKSlZERWJNQmtHQTFVRUF3d1NUV0ZwCmJsTjVj
    M1JsYlNCU2IyOTBJRU5CTUI0WERUSTJNREl4TnpJeE1qazFPVm9YRFRJNE1EVXlNakl4TWprMU9W
    b3cKWkRFTE1Ba0dBMVVFQmhNQ1ZWTXhEakFNQmdOVkJBZ01CVk4wWVhSbE1RMHdDd1lEVlFRSERB
    UkRhWFI1TVJNdwpFUVlEVlFRS0RBcE5ZV2x1VTNsemRHVnRNUXN3Q1FZRFZRUUxEQUpKVkRFVU1C
    SUdBMVVFQXd3TGJXRnBiaTV6CmVYTjBaVzB3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3
    QXdnZ0VLQW9JQkFRRFd5UzFCTmxuc1FXaHQKOUJUME5yWDJpRUxjdXhRQ0xEeGhleUd6MmlJWHZK
    WG9YWVltL3MrK0tYNHV5OXNsUU14QURtSHpkRlZTTFdiKwpralU4RGpDaEFhcFFQdjhiT0d3Z2pI
    UXB0WDNCemV4SWhlQ2UySkFGZm5sa2ZVRzhoRUpzSVgzYm0xMGhkbDVrCnZmUDUwVW05N0VHQ1pr
    VzF2a2ZHZEtEUi83RDI0c2lMQ01vcGY4RjVIaml5eU9hTk1wVGJ5U25GRGluakJTem4KM1o1dW9F
    M2czeFpxNFpxM2Y5TVp5emVySnByY25TSTBGRGFGVlg2dU92eFdwYWFvbGpFNmk0a3F6QUdlWWVR
    TgpENWkrNkEyUXZmU2I1eFdlMUJoZU9nTFAvbm5oM2pvYzhEYmZaOXNEV2hyb3R3aG4yYzJvMGh0
    TG5PcXUvREkzCk56b1JiWGM1QWdNQkFBR2pnWXN3Z1lnd1JnWURWUjBSQkQ4d1BZSVZZMjlzYkdG
    aWIzSmhMbTFoYVc0dWMzbHoKZEdWdGdoVnVaWGgwWTJ4dmRXUXViV0ZwYmk1emVYTjBaVzJDRFNv
    dWJXRnBiaTV6ZVhOMFpXMHdIUVlEVlIwTwpCQllFRkEzTzNqZWl4a2NKd3REOXpnVXpkcUJJWkI0
    dU1COEdBMVVkSXdRWU1CYUFGSTVWMWwrNDhvYXlMcmRrCkg2dlB4U1h3UUYxM01BMEdDU3FHU0li
    M0RRRUJDd1VBQTRJQ0FRQlA2YW5sTzh5OTU3Q0c2L2grMzRPY2ViaHoKNDZNUXdrM2Q5Y21zdHpn
    cnhPQWxGMWplbTltTjkzOE9lY0xqQUZPaHNvZjI2NFdudzZwckZZQ1AvM3ViZGtsWgpTVXpsM01S
    YnFiS1dsbEdtL2tJYmcyOGkxMHlKd08vN2NTZ0hNWis1c1F4cHVSNUxFYzZ1cnNVcno4MEk4dDIz
    CmVqT0JqYmdZallsczlpaU9zUkJOdHpCelVMT1Bxa2p3KzhEYzk4REo4YllIYUkrY2lHNGI0cHl0
    WTdZaUVxN0IKL2NDQVNkcXNWQTdoWUZmcUFqQ0hTb2laSnk1YXgyNEN5bkhEOGhiUUJVVWhHdXBm
    RE1hbGhWSUJUV2RTREI5OQp1SUtTNTR3Z1QrbVBxM0NjZXpFSmkzcVpCQ2dZbmUxZ1pzRXYrbjE4
    T1lmUjdmaHM5Z2xYWkJYUSt2NTdNMDhtCnhUbVZNb1ZScENRbGMzZ3ZoYzJPOXc2QWNJQzY2MjRJ
    Si9sbUJENFArdi9neVMxaWp5SGdJNUI1Y0drRDhUaGEKMjVlcFFWemgyR09teHdXbG5XRUJIRDZS
    VmRzQlJCcEFZd2NuSjZLNUtPeXJvSVREb0tJbm1rTmNuOUVmZCszWgo2OTJ5RVdDQnVDMFZjaXJD
    dG8wQlplRi9hd29rK1NRWkxiOWlOa3haZzNNU1cvdC9mZndlYkV3TlhZNlc0ZkxhCmFucEc0blJD
    YTBvZnVwV1BzMU14MUMrREcvWnRiSzc2SHZ3Znk3TUpIaTZIZlYreXd2aSs0WFZCaXl0ZktrMm4K
    NGQ0T0tnWExYd0wrYitQU0pUcEI3NWkzcVhkb1QzbWJOanNQMHlGdlVOM1dDeEFZeUNpbHdoUitH
    Q1ZaRElWdQpXbUhMdWJPMTVQMmJ1MGE3Y0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktrd2dnU2xBZ0VBQW9JQkFRRFd5UzFCTmxuc1FXaHQKOUJUME5yWDJpRUxjdXhRQ0xEeGhl
    eUd6MmlJWHZKWG9YWVltL3MrK0tYNHV5OXNsUU14QURtSHpkRlZTTFdiKwpralU4RGpDaEFhcFFQ
    djhiT0d3Z2pIUXB0WDNCemV4SWhlQ2UySkFGZm5sa2ZVRzhoRUpzSVgzYm0xMGhkbDVrCnZmUDUw
    VW05N0VHQ1prVzF2a2ZHZEtEUi83RDI0c2lMQ01vcGY4RjVIaml5eU9hTk1wVGJ5U25GRGluakJT
    em4KM1o1dW9FM2czeFpxNFpxM2Y5TVp5emVySnByY25TSTBGRGFGVlg2dU92eFdwYWFvbGpFNmk0
    a3F6QUdlWWVRTgpENWkrNkEyUXZmU2I1eFdlMUJoZU9nTFAvbm5oM2pvYzhEYmZaOXNEV2hyb3R3
    aG4yYzJvMGh0TG5PcXUvREkzCk56b1JiWGM1QWdNQkFBRUNnZ0VBQXBoN3k0WDBvRDVLSE1vT1Zz
    VXlmY0EzenFNVUl0S1dDRGVNdUxleUljZE4KcUhrNDNjL0dndTNOY0pOV0dxVWwwc0JadnE5eE9J
    VUQ4WitpdFE4VzExdEZ5NkozUXNUenlaRG85bmdUQlB5UQpGbkJIdnFPdldlR2xaZWw5bWVHZlM5
    ODd2aU9xaEhVQnZ3WHNwT0E2bStqM0FiUnFzeitSYm55S1ZQOWFEQ0c3CnpYZWlHSXFBbE5pR3NN
    bTVMN0JsOEVSUUNmTnZjREo0ZmJwdU5yMlFheGVQdVdyVlV4Ti9IWlN3djdlK2Z3Z20KSVZ3UWR6
    V1VRR0FCSWZqd1pEZHlzTk45SU9iTjcyZFZJNWhzSkV0RlphTUFCd1J4T0JOVzNldTNqQ1JzUXcz
    VAp4Tm5BdllOMkZUalU3RW8rU0EyZE9GUTBkeDd6ZkM1TlBocDdNdU9uZ1FLQmdRRDRKeExubzNp
    UFpRMWZBaitNCjRFMVQ1b2E0emRKSmZUNGtySytmQXFnRGJ2cXgvZ2Q4d2s0cEVnU1o3TmhKVTVh
    bEk2a0pOYmE3S05mRnpWekoKdHg4ekRoQkNrV3doNUgzZ00vK1Z1VVZoUEV6UU1icGovYjViWEZs
    SE14WGZ6R1diK25CVkQ5WkRva1pYZFVNRQpuNzJESzNTNDU2b3pBVjJpMWhXdEI0ZjlYUUtCZ1FE
    ZGsvc3lvUHg5UjJ6TVZlWE5sUnhTMkJaaUF3cEwxRm8wCklHQncwaTdkb0hHMFJUekpUTmtKVytF
    RHdMdUFlZks0RFIrWTIrTjJtMGpkK21TTEhYbnVrZXNnK2wycUFKZU8KaWJCcmhJaEVtaUc4VkFz
    QVZKOGhjdElKTy9MUWpsVEwwSTJYRHR0ck11SHdWMGM1VjZqUENJcGhVTDRvY1pFcgpzV0hHeHdq
    bmpRS0JnUUN2NFhIaXY5aEpPZ1E2SEt2U080QlRRUWFub1NtMGNKSkZDQ2dKZWFaL21IOFMvTXR0
    CnY0SUtWZnp3NUErQUdVQ2lseDNOcTBaeWJNWlNLZlhqK21pZ2xRMHRRVWowMUsvcTRxLzUvTENS
    OUYwMUNxbmoKQ1F1TVVXM3RxdVdNRTZESTVyNExiQWdmTTdyTGJnOHNEZFFTVGhDU3BZL2FTdE9G
    QUZ1b29iZmUrUUtCZ1FDSgo3N3RxOHlqN1hHRndldkRLSUU4M2kybXpyaXpVcytkTGwvUXhoOGJC
    RlVaemNMNjhtZWhxbVJYazNqQmJkSThTCjRLaVE0aUlpRGQwNHdzMmdoTU1KTHpGdW9DMTZ6VStM
    M2s5RFA0Z05ITjV2Zk9vMFZIbVR1d1RoMXIzNzh2NzYKdW1QS2ErZFFQcWJFbGJDekU4ejB4VjVQ
    NHBIZVg0Ujk3TGp2bzZ2NWFRS0JnUUNCRFo5SkZzNEovR3RUOFJ6SAptN0k0VTgrL0h5bVBmckpq
    blB0K0k4RDUzcUxISGFtTHhhbUsrRmZoankyVDNXRHowWmNYRHRpUWNzZ1h1UUhrCkFrLzQxc04r
    R1JsM2hFbk5Oc0VELzc0blBiUEh1NitPYm53RTBqenN1dGlnU2FoTmdmU1hDYWZSUmYxYmNUMXcK
    Sk1nZER3bVErOXM0LzJIS1Z6ZHZXc1dhRVE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-ca
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud-ca
    app.kubernetes.io/instance: nextcloud
type: Opaque
data:
  rootca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ0ekNDQTUrZ0F3SUJBZ0lVWWFndTBhc0pw
    c21mVWdjWjIwSk9wdHhPWndZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2F6RUxNQWtHQTFVRUJoTUNW
    Vk14RGpBTUJnTlZCQWdNQlZOMFlYUmxNUTB3Q3dZRFZRUUhEQVJEYVhSNQpNUk13RVFZRFZRUUtE
    QXBOWVdsdVUzbHpkR1Z0TVFzd0NRWURWUVFMREFKSlZERWJNQmtHQTFVRUF3d1NUV0ZwCmJsTjVj
    M1JsYlNCU2IyOTBJRU5CTUI0WERUSTJNREl4TnpJeE1qazFPVm9YRFRNMk1ESXhOVEl4TWprMU9W
    b3cKYXpFTE1Ba0dBMVVFQmhNQ1ZWTXhEakFNQmdOVkJBZ01CVk4wWVhSbE1RMHdDd1lEVlFRSERB
    UkRhWFI1TVJNdwpFUVlEVlFRS0RBcE5ZV2x1VTNsemRHVnRNUXN3Q1FZRFZRUUxEQUpKVkRFYk1C
    a0dBMVVFQXd3U1RXRnBibE41CmMzUmxiU0JTYjI5MElFTkJNSUlDSWpBTkJna3Foa2lHOXcwQkFR
    RUZBQU9DQWc4QU1JSUNDZ0tDQWdFQWtHQkwKN1hPZXpoVnNoaDAwNm1YTkQ2cUJsd3VDZ1QxZnRX
    QzE4QUNCVm14MllyZU1CSWZSdWRvTU5qQkZmMlliNVJlNwpib1lPanJvdW0wQXkrdnFPai85dXds
    c0NKTm4xOEVWUk9vakIwNVp6blhYS1BaeWFsK2ErU2VFWWsrMzNQRHVzClc3dE9yVjNqN1NDTXMr
    MTJZcTZ5aDJXZmxUMlpiZ2l3cWJ5V3dKb3dTSzFJNEN0Ry9XbWUrTEp2MSszMEFod2sKM3JVSW5U
    Y0VLMi9XenNWbHl3NlF5VUszVVNiQ1dGVmdFemxuY0xVM21RVU1tdTkxY3pWK2o5ZHpXUVlCZTRr
    KwpKNWRtam9INlQ1SzdlVDFEazY3eUt3OUxuSnBJOGNmYUJibkt4c3F5Sm1NNEU1TDNFSWI5WWJj
    UlpXR0JKcnBECk1kZS9mRlB6Zjg4ejdBKzB4US9KcHovSWhEWVNFR1dOMk8vWkxUTG0yZDYyRklw
    Q3E3cUV6cFpvTGJKam1PSGkKaTZYNjdHZHMxL1BrbjZmVDBlbnlsMkkybE5DUkxsaWo5bVFxSXQ5
    cGs3TE5SUGp2NUh0c0Z3M0NXQjMvOSs1VworclR2aGRFOEY0QWcxUVExNTFYTnVHMmoxekJ2MWlN
    eVNIazJpeG1hSUhDOHU2dnNURTVqMW5jWW1UT1hmT3pLCk9ucENvUmp5SkcyNVVGc0VkL3Z4SGJF
    WTkycGpDZlc5QlF5L0lLNVZlOTIvdnpzU0ZhekQ0RldpS0xldnFQalkKNXZnQW1rdkU2NlpnbzZJ
    Y0QrenQ0Yis1SmR5U2diLzk4M1hpQ1FySU1jS2NFcjlzaTQzeXNnSm85Q09jMEhZdgpwZS8rMzFn
    SW9idDFVYVFxS1h1Ujl5OEhZRm5KVjdsWG5hYWtheWtDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllF
    CkZJNVYxbCs0OG9heUxyZGtINnZQeFNYd1FGMTNNQjhHQTFVZEl3UVlNQmFBRkk1VjFsKzQ4b2F5
    THJka0g2dlAKeFNYd1FGMTNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVM
    QlFBRGdnSUJBR1dEelcxWApxOEFVTTVDUGxlUmZudTY5RkZpMTJLTHdkdEZqQ1BBbjlGcW5Rd1Y1
    SXhkV3dhdEx0VyttT21mb2huTFpZaFJICmZxYzYwVVNvTXNpQUlaY01ENmJCL2lWOGlMeXZadEY2
    eHhIWWVReDdEL0dWYmRraTQyQS8zUS85WTgxa3ZQaGMKTXZvR0huN1VjZUR1TmhjaFlENUlTL0Zk
    OVBGRGdJalJxL0xGazdhUTR0NlE4dk1qOG9rU1F5L2t5L29FUGpyNAo3OExlazg1b0c4Ky9DcHc2
    TVpJU3lEVTA5UFpHMDBOcmRiMnVQQUljcXBXc2FWeWd3NVBRcGc0UG9ab0JpZm1jCnZiM1I0Yndi
    VzdmS05aTWdZVkhXRUNqam5nZlVON1hmcFBDcXBJSWpNOG80ZGcyajFLaDBFWGlIdmoxNisvUS8K
    UGxrQjI2K1Y1OXJKSWFidGhBYkN3K212RWZVdzVlUmRXS1dZNWRlUmwzcVkwSlBRNXFNaDc0UHNI
    a21KK2lyTApDSWFVd01HRjlCY1ZjQWhTdzFVUTRDOUNZa041NnpWOWhDSGdsOUZJTE9qVUJHTEZw
    OGIwVytkM0d5aXpFbmFQClg2aG1DSUFHK01kWlMyblBZQzFpU2lpeXllR29DdEJWamNiNDNOdjFl
    bktJZ3FXYUdMSittUWFmbGp5YlFmWG0KTzVER1dPOGFQWHIzUTVKWHVxS2N1QUhTVU5tNWl4VE5l
    QUJOVnJOTktWWXNXQlBPOXp4RGI0dndPWDY2SEhMWgpCZmFOckhOd1hNQ2pWcUJ0aHN6Tncvb1VY
    UkQ5amVtU2dvL0lmcUNqdytZYkIzWUVESFVpeWZub3VLcmdnVktaCktXcStRbHVPUmJnMFZCZUhE
    b1N3VldHRmtrb2RyYVpGUEJqKwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

