apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  default.server: |
    nextcloud.main.system collabora.main.system {
        hosts {
              192.168.1.21 nextcloud.main.system collabora.main.system
              fallthrough
        }
    }
